ALTER TABLE user MODIFY COLUMN password VARCHAR(50);
ALTER TABLE user ADD COLUMN op_issuer VARCHAR(100);
ALTER TABLE user ADD COLUMN op_userid VARCHAR(100);
ALTER TABLE user ADD COLUMN avatar VARCHAR(200);